#!/bin/bash

# Папка с обоями
WALLPAPER_DIR="$HOME/Pictures/wal"

echo "Default wallpapers folder in script $WALLPAPER_DIR. Select installation method:"
echo "1) Choose from preview (sxiv)"
echo "2) Choose random"
read -p "Choose 1 or 2: " CHOICE

if [[ "$CHOICE" == "1" ]]; then
    echo "Открыл предпросмотр. Наводишь на нужную картинку, жмёшь Enter (НЕ q!)"

    USER_FILE=$(sxiv -ot "$WALLPAPER_DIR")
    
    if [[ -z "$USER_FILE" ]]; then
        echo "Ты ничего не выбрал. Вали."
        exit 1
    fi

    SELECTED_WALL="$USER_FILE"

elif [[ "$CHOICE" == "2" ]]; then
    SELECTED_WALL=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
    if [[ ! -f "$SELECTED_WALL" ]]; then
        echo "No wallpapers in $WALLPAPER_DIR"
        exit 1
    fi
else
    echo "Invalid input! Exit."
    exit 1
fi

# Применяем обои
feh --bg-scale "$SELECTED_WALL"
wal -i "$SELECTED_WALL"

# Xresources
xrdb -merge ~/.Xresources

if [ -z "$WAL_EXECUTED" ]; then
    export WAL_EXECUTED=1
    wal -R
fi

# Dunst
source ~/.cache/wal/colors.sh

DUNST_CONFIG="$HOME/.config/dunst/dunstrc"

sed -i "s/frame_color = .*/frame_color = \"$color1\"/" "$DUNST_CONFIG"
sed -i "s/foreground = .*/foreground = \"$color15\"/" "$DUNST_CONFIG"
sed -i "s/background = .*/background = \"$color0\"/" "$DUNST_CONFIG"

pkill dunst && dunst &

# Alacritty
WAL_COLORS_FILE=~/.cache/wal/colors-alacritty.toml
ALACRITTY_CONFIG=~/.config/alacritty/alacritty.toml

cat "$WAL_COLORS_FILE" > "$ALACRITTY_CONFIG"

echo "Alacritty updated with colors and opacity."

# Waybar
pkill -SIGUSR2 waybar

# Telegram
wal-telegram

# Firefox
pywalfox update
